import React, { useState } from "react";
import Waters from '/src/assets/PrincipalLogos/RowTwo/waters.svg';
import Labomatic from '/src/assets/PrincipalLogos/RowTwo/Labomatic.svg';
import ECom from '/src/assets/PrincipalLogos/RowTwo/ECom.png';

import ImgSeparchromPC01 from "/images/products/Ecom/separchrom-pc01.png";
import ImgSeparchromPC02 from "/images/products/Ecom/separchrom-pc02.png";
import ImgSeparchromPC04 from "/images/products/Ecom/separchrom-pc04.png";
import ImgSeparchromPC06 from "/images/products/Ecom/separchrom-pc06.png";
import ImgSeparchromPC08 from "/images/products/Ecom/separchrom-pc08.png";
import ImgSeparpress from "/images/products/Ecom/separpress.png";
import ImgSeparsys400 from "/images/products/Ecom/Separsys-400.png";

import Banner1 from "/images/products/Banner/Banner1.jpg";
import Banner2 from "/images/products/Banner/Banner2.jpg";
import Banner3 from "/images/products/Banner/Banner3.jpg";


export const EcomProducts = {
  "separchrom-pc01": {
    id: "separchrom-pc01",
    name: "Separchrom PC01 Columns For Preparative Chromatography",
    image: ImgSeparchromPC01,
    logo: ECom,
    bannerImg: Banner3,
    altText: "Ecom",
    videoId: "",
    meta: {
      title: "SEPARCHROM PC01 Columns | Industrial Chromatography Columns | Inkarp India",
      description:
        "Explore the SEPARCHROM PC01 Industrial Chromatography Columns from Ecom, designed for precision, scalability, and industrial-scale purification. Distributed and supported by Inkarp Instruments across India.",
      keywords: [
        "SEPARCHROM PC01 Columns",
        "Industrial Chromatography Columns",
        "Ecom Column Systems",
        "HPLC Industrial Columns",
        "Preparative Chromatography India",
        "Inkarp Ecom Instruments",
        "Large ID Chromatography Columns",
        "Inkarp Chromatography Solutions",
        "Industrial Process Columns"
      ],
      altText: "SEPARCHROM PC01 Industrial Column",
      internalLinks: ["analytical-and-chromatography-solutions"],
      externalLinks: ["https://www.waters.com/nextgen/us/en.html"]
    },
    description: `
        <div style="display: flex; flex-direction: column; gap: 1.5rem; font-family: Roboto, sans-serif;">
          <div style="display: flex; flex-direction: column;">
            <div style="margin-top: 1rem; color: #444; font-size: 18px; line-height: 1.8;">
              <p style="margin-bottom: 10px;  font-family:MaxOT><strong>HPLC COLUMNS FOR PREP CHROMATOGRAPHY</strong></p>
              <p style="margin-bottom: 10px;"><strong>High performance Columns with biaxial compression</strong></p>
              <p style="margin-bottom: 10px;">
                Columns Separchrom PC01 correspond to the highest requirements of preparative liquid chromatography. PC01 columns are designed to be used in a mode of axial (or biaxial) compression. Columns can be packed by dynamic slurry technique or by sedimentation method. They are equipped with identical pistons on input and output. Pistons are provided by Poremet® 2 stainless steel (AISI 316 L) frits with porosity 3 µm and minimum hydraulic resistance. New developed patented liquid distributing system is installed under each frit. The design guarantees perfect piston flow, high efficiency even for high injection volume and simple accessibility of frit for cleaning.
              </p>
              <p style="margin-bottom: 10px;">
              Separchrom PC01 columns are made of high quality stainless steel (AISI 316 or AISI 316L on the request) and their inner surface is polished to reach Ra < 0,3 µm. Column flanges are not welded, but screwed on the column tube. It means that there is no temperature increasing during manufacture and thus no change of steel properties. Columns have input piston with large stroke (possibly through whole column length) and it is moved by a force generated by a hydraulic cylinder or by flange bolts tightening. Single hydraulic cylinders fitted on upper flange with manual oil pumps are offered as well as fully automated electric motor driven devices for columns’ packing/unpacking procedure. Separchrom PC01 column output pistons movement is provided mechanically by tightening the flange bolts. In this case is functional stroke of the piston approximately 15 % of the column I.D. Pistons are sectional, frit squeezed to the frit ring can be released from piston body and cleaned as well the flow distributor. Distributor design effectively protects the frit from particles which can caused i´their blockage.
              </p>
              <p style="margin-bottom: 10px;">
                Separchrom PC01 columns are delivered with stainless steel legs attached to the upper flange for full accessibility. Optional accessories like filling adapters, slurry vessels, pumps, and automation modules support dynamic slurry technique or emptying procedures.
              </p>
              <p style="margin-bottom: 10px;">
              Separchrom PC01 columns are completed by a broad scale of accessories as filling adapters, slurry mixing vessels, slurry transporting pumps etc. for automatic filling using dynamic slurry technique as well as automatic emptying procedure.
              </p>
            </div>
          </div>
          <div style="">
            <h2 class=" font-[MaxOT] text-xl text-[#E63946] py-3">Columns for Laboratory Applications</h2>
            <div style="overflow-x: auto;">
              <table style="width: 100%; border-collapse: collapse; font-size: 15px; border: 1px solid #ccc;">
                <thead>
                  <tr style="background-color: #f5f5f5; text-align: left;">
                    <th style="padding: 10px; border: 1px solid #ccc;">Type of column</th>
                    <th style="padding: 10px; border: 1px solid #ccc;">I.D. (mm)</th>
                    <th style="padding: 10px; border: 1px solid #ccc;">Length (mm)</th>
                    <th style="padding: 10px; border: 1px solid #ccc;">Pressure (bar)</th>
                    <th style="padding: 10px; border: 1px solid #ccc;">Note</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01 25/50</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">25</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">50</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">200</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">Delivered without legs</td>
                  </tr>
                  <tr>
                    <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01 25/100</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">25</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">100</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">200</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">Delivered without legs</td>
                  </tr>
                  <tr>
                    <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01 25/250</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">25</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">250</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">200</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">Delivered without legs</td>
                  </tr>
                  <tr>
                    <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01 50/50</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">50</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">50</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">200</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">Delivered without legs</td>
                  </tr>
                  <tr>
                    <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01 50/100</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">50</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">100</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">200</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">—</td>
                  </tr>
                  <tr>
                    <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01 50/250</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">50</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">250</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">200</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">—</td>
                  </tr>
                  <tr>
                    <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01 50/500</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">50</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">500</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">200</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">—</td>
                  </tr>
                  <tr>
                    <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01 100/100</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">100</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">100</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">150</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">—</td>
                  </tr>
                  <tr>
                    <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01 100/250</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">100</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">250</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">150</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">—</td>
                  </tr>
                  <tr>
                    <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01 100/500</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">100</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">500</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">150</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">—</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
          <div style="margin-top: 2rem;">
            <h2 class=" font-[MaxOT] text-xl text-[#E63946] py-3">Columns for Industrial Applications</h2>
            <div style="overflow-x: auto;">
              <table style="width: 100%; border-collapse: collapse; font-size: 15px; border: 1px solid #ccc;">
                <thead>
                  <tr style="background-color: #f5f5f5; text-align: left;">
                    <th style="padding: 10px; border: 1px solid #ccc;">Type of column</th>
                    <th style="padding: 10px; border: 1px solid #ccc;">I.D. (mm)</th>
                    <th style="padding: 10px; border: 1px solid #ccc;">Length (mm)</th>
                    <th style="padding: 10px; border: 1px solid #ccc;">Pressure (bar)</th>
                    <th style="padding: 10px; border: 1px solid #ccc;">Note</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01-100/100</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">100</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">100</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">150</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">—</td>
                  </tr>
                  <tr>
                    <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01-100/250</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">100</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">250</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">150</td>
                    <td style="padding: 10px; border: 1px solid #ccc;">—</td>
                  </tr>
                  <tr>
          <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01-100/500</td>
          <td style="padding: 10px; border: 1px solid #ccc;">100</td>
          <td style="padding: 10px; border: 1px solid #ccc;">500</td>
          <td style="padding: 10px; border: 1px solid #ccc;">150</td>
          <td style="padding: 10px; border: 1px solid #ccc;">—</td>
        </tr>
        <tr>
          <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01-100/600</td>
          <td style="padding: 10px; border: 1px solid #ccc;">100</td>
          <td style="padding: 10px; border: 1px solid #ccc;">600</td>
          <td style="padding: 10px; border: 1px solid #ccc;">150</td>
          <td style="padding: 10px; border: 1px solid #ccc;">—</td>
        </tr>
        <tr>
          <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01-100/700</td>
          <td style="padding: 10px; border: 1px solid #ccc;">100</td>
          <td style="padding: 10px; border: 1px solid #ccc;">700</td>
          <td style="padding: 10px; border: 1px solid #ccc;">150</td>
          <td style="padding: 10px; border: 1px solid #ccc;">—</td>
        </tr>
        <tr>
          <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01-100/800</td>
          <td style="padding: 10px; border: 1px solid #ccc;">100</td>
          <td style="padding: 10px; border: 1px solid #ccc;">800</td>
          <td style="padding: 10px; border: 1px solid #ccc;">150</td>
          <td style="padding: 10px; border: 1px solid #ccc;">—</td>
        </tr>
        <tr>
          <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01-100/1000</td>
          <td style="padding: 10px; border: 1px solid #ccc;">100</td>
          <td style="padding: 10px; border: 1px solid #ccc;">1000</td>
          <td style="padding: 10px; border: 1px solid #ccc;">150</td>
          <td style="padding: 10px; border: 1px solid #ccc;">—</td>
        </tr>
        <tr>
          <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01-150/150</td>
          <td style="padding: 10px; border: 1px solid #ccc;">150</td>
          <td style="padding: 10px; border: 1px solid #ccc;">150</td>
          <td style="padding: 10px; border: 1px solid #ccc;">150</td>
          <td style="padding: 10px; border: 1px solid #ccc;">—</td>
        </tr>
        <tr>
          <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01-150/300</td>
          <td style="padding: 10px; border: 1px solid #ccc;">150</td>
          <td style="padding: 10px; border: 1px solid #ccc;">300</td>
          <td style="padding: 10px; border: 1px solid #ccc;">150</td>
          <td style="padding: 10px; border: 1px solid #ccc;">—</td>
        </tr>
        <tr>
          <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01-150/500</td>
          <td style="padding: 10px; border: 1px solid #ccc;">150</td>
          <td style="padding: 10px; border: 1px solid #ccc;">500</td>
          <td style="padding: 10px; border: 1px solid #ccc;">150</td>
          <td style="padding: 10px; border: 1px solid #ccc;">—</td>
        </tr>
        <tr>
          <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01-150/600</td>
          <td style="padding: 10px; border: 1px solid #ccc;">150</td>
          <td style="padding: 10px; border: 1px solid #ccc;">600</td>
          <td style="padding: 10px; border: 1px solid #ccc;">150</td>
          <td style="padding: 10px; border: 1px solid #ccc;">—</td>
        </tr>
        <tr>
          <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01-150/900</td>
          <td style="padding: 10px; border: 1px solid #ccc;">150</td>
          <td style="padding: 10px; border: 1px solid #ccc;">900</td>
          <td style="padding: 10px; border: 1px solid #ccc;">150</td>
          <td style="padding: 10px; border: 1px solid #ccc;">—</td>
        </tr>
        <tr>
          <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01-150/1000</td>
          <td style="padding: 10px; border: 1px solid #ccc;">150</td>
          <td style="padding: 10px; border: 1px solid #ccc;">1000</td>
          <td style="padding: 10px; border: 1px solid #ccc;">150</td>
          <td style="padding: 10px; border: 1px solid #ccc;">—</td>
        </tr>
        <tr>
          <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01-200/200</td>
          <td style="padding: 10px; border: 1px solid #ccc;">200</td>
          <td style="padding: 10px; border: 1px solid #ccc;">200</td>
          <td style="padding: 10px; border: 1px solid #ccc;">120</td>
          <td style="padding: 10px; border: 1px solid #ccc;">—</td>
        </tr>
        <tr>
          <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01-200/400</td>
          <td style="padding: 10px; border: 1px solid #ccc;">200</td>
          <td style="padding: 10px; border: 1px solid #ccc;">400</td>
          <td style="padding: 10px; border: 1px solid #ccc;">120</td>
          <td style="padding: 10px; border: 1px solid #ccc;">—</td>
        </tr>
        <tr>
          <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01-200/500</td>
          <td style="padding: 10px; border: 1px solid #ccc;">200</td>
          <td style="padding: 10px; border: 1px solid #ccc;">500</td>
          <td style="padding: 10px; border: 1px solid #ccc;">120</td>
          <td style="padding: 10px; border: 1px solid #ccc;">—</td>
        </tr>
        <tr>
          <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01-200/600</td>
          <td style="padding: 10px; border: 1px solid #ccc;">200</td>
          <td style="padding: 10px; border: 1px solid #ccc;">600</td>
          <td style="padding: 10px; border: 1px solid #ccc;">120</td>
          <td style="padding: 10px; border: 1px solid #ccc;">—</td>
        </tr>
        <tr>
          <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01-200/800</td>
          <td style="padding: 10px; border: 1px solid #ccc;">200</td>
          <td style="padding: 10px; border: 1px solid #ccc;">800</td>
          <td style="padding: 10px; border: 1px solid #ccc;">120</td>
          <td style="padding: 10px; border: 1px solid #ccc;">—</td>
        </tr>
        <tr>
          <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01-200/1000</td>
          <td style="padding: 10px; border: 1px solid #ccc;">200</td>
          <td style="padding: 10px; border: 1px solid #ccc;">1000</td>
          <td style="padding: 10px; border: 1px solid #ccc;">120</td>
          <td style="padding: 10px; border: 1px solid #ccc;">—</td>
        </tr>
        <tr>
          <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01-300/300</td>
          <td style="padding: 10px; border: 1px solid #ccc;">300</td>
          <td style="padding: 10px; border: 1px solid #ccc;">300</td>
          <td style="padding: 10px; border: 1px solid #ccc;">100</td>
          <td style="padding: 10px; border: 1px solid #ccc;">—</td>
        </tr>
        <tr>
          <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01-300/600</td>
          <td style="padding: 10px; border: 1px solid #ccc;">300</td>
          <td style="padding: 10px; border: 1px solid #ccc;">600</td>
          <td style="padding: 10px; border: 1px solid #ccc;">100</td>
          <td style="padding: 10px; border: 1px solid #ccc;">—</td>
        </tr>
        <tr>
          <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01-300/900</td>
          <td style="padding: 10px; border: 1px solid #ccc;">300</td>
          <td style="padding: 10px; border: 1px solid #ccc;">900</td>
          <td style="padding: 10px; border: 1px solid #ccc;">100</td>
          <td style="padding: 10px; border: 1px solid #ccc;">—</td>
        </tr>
        <tr>
          <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01-300/1200</td>
          <td style="padding: 10px; border: 1px solid #ccc;">300</td>
          <td style="padding: 10px; border: 1px solid #ccc;">1200</td>
          <td style="padding: 10px; border: 1px solid #ccc;">100</td>
          <td style="padding: 10px; border: 1px solid #ccc;">—</td>
        </tr>
        <tr>
          <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01-400/400</td>
          <td style="padding: 10px; border: 1px solid #ccc;">400</td>
          <td style="padding: 10px; border: 1px solid #ccc;">400</td>
          <td style="padding: 10px; border: 1px solid #ccc;">80</td>
          <td style="padding: 10px; border: 1px solid #ccc;">—</td>
        </tr>
        <tr>
          <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01-400/800</td>
          <td style="padding: 10px; border: 1px solid #ccc;">400</td>
          <td style="padding: 10px; border: 1px solid #ccc;">800</td>
          <td style="padding: 10px; border: 1px solid #ccc;">80</td>
          <td style="padding: 10px; border: 1px solid #ccc;">—</td>
        </tr>
        <tr>
          <td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC01-400/1200</td>
          <td style="padding: 10px; border: 1px solid #ccc;">400</td>
          <td style="padding: 10px; border: 1px solid #ccc;">1200</td>
          <td style="padding: 10px; border: 1px solid #ccc;">80</td>
          <td style="padding: 10px; border: 1px solid #ccc;">—</td>
        </tr>

                </tbody>
              </table>
            </div>
          </div>
        </div>
        `

  },

  "separchrom-pc02": {
    id: "separchrom-pc02",
    name: "Separchrom PC02 Columns For Preparative Chromatography",
    image: ImgSeparchromPC02,
    logo: ECom,
    bannerImg: Banner3,
    altText: "Ecom",
    videoId: "",
    meta: {
      title: "SSeparchrom PC02 Columns For Preparative Chromatography (DAC Columns, 50mm-1000mm ID Columns) Distributor & Service Provider In India - Ecom - Inkarp Instruments Pvt Ltd",
      description:
        "Explore the SEPARCHROM PC02 Industrial Chromatography Columns from Ecom, designed for precision, scalability, and industrial-scale purification. Distributed and supported by Inkarp Instruments across India.",
      keywords: [
        "SEPARCHROM PC02 Columns",
        "Industrial Chromatography Columns",
        "Ecom Column Systems",
        "HPLC Industrial Columns",
        "Preparative Chromatography India",
        "Inkarp Ecom Instruments",
        "Large ID Chromatography Columns",
        "Inkarp Chromatography Solutions",
        "Industrial Process Columns"
      ],
      altText: "SEPARCHROM PC02 Industrial Column",
      internalLinks: ["analytical-and-chromatography-solutions"],
      externalLinks: ["https://www.waters.com/nextgen/us/en.html"]
    },
    description: `
<div  class="text-[18px]">
  <p class=" font-[MaxOT] text-xl py-3">
    <strong>MPLC Columns for Prep Chromatography</strong><br>
    
  </p>
  <p><strong>Columns for Medium Pressure with Axial Bed Compression</strong></p>
  <p style="line-height: 1.6; margin-bottom: 1rem;">
Separchrom PC02 medium pressure stainless steel column are intended for separation where high pressure is not necessary, but high efficiency can be still expected and useful. Separchrom PC02 thus fill requirements of many users. They are made of cutted and polished stainless steel tubes and equipped on input either with ultra high molecular weight polyethylene made pistons (PC 02 UP) with steel support or stainless steel made pistons (PC 02 SP), both with Poremet® 5 stainless steel (AISI 316 L) frits with 02 porosity 5 µm and minimum hydraulic resistance. Flow distributors with groves for liquid distribution are incorporated in to the piston and the system guarantees perfect piston flow with nearly zero pressure drop. Columns have functional stroke of the input piston approximately 60 % of the inner diameter of the column when working with flange bolts and even higher when hydraulic cylinder is used.
  </p>
  <p style="line-height: 1.6; margin-bottom: 1rem;">
    Outputs of PC02 columns are designed as fix units (pistons on special request) and use the same flow distributors and frits like input pistons.
  </p>

  <p style="line-height: 1.6; margin-bottom: 1rem;">
   Due the low movement resistance of UHMWE pistons Separchrom PC02 columns can be equipped with special software application in order to compensate swelling and deswelling of organic sorbents in different mobile phases (column piston is moved in very small steps up and down during use).
  </p>

  <!-- Table: Lab Applications -->
  <h2 class=" font-[MaxOT] text-xl text-[#E63946] py-3">Columns for Laboratory Applications</h2>
  <div style="overflow-x: auto;">
    <table style="width: 100%; border-collapse: collapse; font-size: 15px; border: 1px solid #ccc;">
      <thead>
        <tr style="background-color: #f5f5f5; text-align: left;">
          <th style="padding: 10px; border: 1px solid #ccc;">Type of Column</th>
          <th style="padding: 10px; border: 1px solid #ccc;">I.D. (mm)</th>
          <th style="padding: 10px; border: 1px solid #ccc;">Length (mm)</th>
          <th style="padding: 10px; border: 1px solid #ccc;">Pressure (Bar)</th>
          <th style="padding: 10px; border: 1px solid #ccc;">Note</th>
        </tr>
      </thead>
      <tbody>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC02-25/50</td><td>25</td><td>50</td><td>70</td><td>—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC02-25/250</td><td>25</td><td>250</td><td>70</td><td>—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC02-50/250</td><td>50</td><td>250</td><td>50</td><td>—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC02-50/500</td><td>50</td><td>500</td><td>50</td><td>—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC02-100/250</td><td>100</td><td>250</td><td>40</td><td>—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC02-100/500</td><td>100</td><td>500</td><td>40</td><td>—</td></tr>
      </tbody>
    </table>
  </div>

  <!-- Table: Industrial Applications -->
  <h2 class=" font-[MaxOT] text-xl text-[#E63946] py-3">Columns for Industrial Applications</h2>
  <div style="overflow-x: auto;">
    <table style="width: 100%; border-collapse: collapse; font-size: 15px; border: 1px solid #ccc; padding:5px;">
      <thead>
        <tr style="background-color: #f5f5f5; text-align: left;">
          <th style="padding: 10px; border: 1px solid #ccc;">Type of Column</th>
          <th style="padding: 10px; border: 1px solid #ccc;">I.D. (mm)</th>
          <th style="padding: 10px; border: 1px solid #ccc;">Length (mm)</th>
          <th style="padding: 10px; border: 1px solid #ccc;">Pressure (Bar)</th>
          <th style="padding: 10px; border: 1px solid #ccc;">Note</th>
        </tr>
      </thead>
      <tbody>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC02-100/250</td><td>100</td><td>250</td><td>40</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC02-100/500</td><td>100</td><td>500</td><td>40</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC02-150/300</td><td>150</td><td>300</td><td>40</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC02-150/600</td><td>150</td><td>600</td><td>40</td><td>—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC02-200/400</td><td>200</td><td>400</td><td>35</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC02-200/700</td><td>200</td><td>700</td><td>35</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC02-200/800</td><td>200</td><td>800</td><td>35</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC02-200/1200</td><td>200</td><td>1200</td><td>35</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC02-300/300</td><td>300</td><td>300</td><td>30</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC02-300/600</td><td>300</td><td>600</td><td>30</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC02-300/700</td><td>300</td><td>700</td><td>30</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC02-400/400</td><td>400</td><td>400</td><td>20</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC02-400/800</td><td>400</td><td>800</td><td>20</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC02-400/1200</td><td>400</td><td>1200</td><td>20</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC02-500/500</td><td>500</td><td>500</td><td>10</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC02-500/1000</td><td>500</td><td>1000</td><td>10</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC02-500/1200</td><td>500</td><td>1200</td><td>10</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC02-600/600</td><td>600</td><td>600</td><td>5</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC02-600/1200</td><td>600</td><td>1200</td><td>5</td><td>—</td></tr>
      </tbody>
    </table>
  </div>
</div>
`


  },

  "separchrom-pc04": {
    id: "separchrom-pc04",
    name: "Separchrom PC04 Columns For Preparative Chromatography",
    image: ImgSeparchromPC04,
    logo: ECom,
    bannerImg: Banner3,
    altText: "Ecom",
    videoId: "",
    meta: {
      title: "Separchrom PC04 Columns For Preparative Chromatography (DAC Columns, 50mm-1000mm ID Columns) Distributor & Service Provider In India - Ecom - Inkarp Instruments Pvt Ltd",
      description:
        "Explore the SEPARCHROM PC04 Industrial Chromatography Columns from Ecom, designed for precision, scalability, and industrial-scale purification. Distributed and supported by Inkarp Instruments across India.",
      keywords: [
        "SEPARCHROM PC04 Columns",
        "Industrial Chromatography Columns",
        "Ecom Column Systems",
        "HPLC Industrial Columns",
        "Preparative Chromatography India",
        "Inkarp Ecom Instruments",
        "Large ID Chromatography Columns",
        "Inkarp Chromatography Solutions",
        "Industrial Process Columns"
      ],
      altText: "SEPARCHROM PC04 Industrial Column",
      internalLinks: ["analytical-and-chromatography-solutions"],
      externalLinks: ["https://www.waters.com/nextgen/us/en.html"]
    },
    description: `
<div  class="text-[18px] space-y-4">
  <h2 style="font-size: 24px; font-weight: bold;  margin-bottom: 1rem;" class="font-[MaxOT]" class="py-3">
    SEPARCHROM PC04 Columns for Preparative Chromatography
  </h2>
  <p style="font-size: 16px; margin-bottom: 1rem;">
    <strong>UHMWPE Columns for Prep Chromatography</strong><br>  
  </p>
  <p style="font-size: 18px; line-height: 1.6; margin-bottom: 1rem;">
  Inkarp Instruments, in partnership with Ecom, offers Separchrom PC04 Columns, a premium solution for preparative chromatography in India. These DAC (Dynamic Axial Compression) columns, available in 50mm-1000mm ID, ensure high-efficiency separations, scalability, and reproducibility. With Inkarp Instruments' expertise and Ecom's innovative technology, we deliver comprehensive support, including installation, training, and after-sales service, to meet your laboratory needs and enhance your chromatography workflow.
  </p>
  <p style="font-size: 18px; line-height: 1.6; margin-bottom: 1rem;">
   For flash chromatography are usually intended polyethylene cartridge columns. Metal free columns are requested in some special applications too. Separlab offers Separchrom PC04 columns for both these purposes. Columns are made of high quality ultra high molecular weight polyethylene, have similar design like stainless steel columns PC01 or PC02 and are equipped with polypropylene fabrics (non woven polypropylene 10 µm pores) made frits. Piston on the input moved by a robust central screw increases the efficiency due an elimination of free space between upper sorbent layer and frit with low pressure flow distributor. Output frit with flow distributor is incorporated in output flange. Columns are compatible with nearly all organic solvents and with all water solutions. Columns are designated for low pressure and medium pressure liquid chromatography.
  </p>

  <!-- Table: PC04 UHMWPE Columns -->
  <h2 class=" font-[MaxOT] text-xl text-[#E63946] py-3"">Column Specifications</h2>
  <div style="overflow-x: auto;">
    <table style="width: 100%; border-collapse: collapse; font-size: 15px; border: 1px solid #ccc;">
      <thead>
        <tr style="background-color: #f5f5f5; text-align: left;">
          <th style="padding: 10px; border: 1px solid #ccc;">Type of Column</th>
          <th style="padding: 10px; border: 1px solid #ccc;">I.D. (mm)</th>
          <th style="padding: 10px; border: 1px solid #ccc;">Length (mm)</th>
          <th style="padding: 10px; border: 1px solid #ccc;">Pressure (bar)</th>
          <th style="padding: 10px; border: 1px solid #ccc;">Note</th>
        </tr>
      </thead>
      <tbody>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC04-50/150</td><td>50</td><td>150</td><td>16</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC04-50/250</td><td>50</td><td>250</td><td>16</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC04-50/300</td><td>50</td><td>300</td><td>16</td><td>—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC04-50/500</td><td>50</td><td>500</td><td>16</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC04-100/250</td><td>100</td><td>250</td><td>16</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC04-100/300</td><td>100</td><td>300</td><td>16</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC04-100/500</td><td>100</td><td>500</td><td>16</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC04-150/300</td><td>150</td><td>300</td><td>6</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC04-150/600</td><td>150</td><td>600</td><td>6</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC04-200/400</td><td>200</td><td>400</td><td>6</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC04-200/800</td><td>200</td><td>800</td><td>6</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC04-300/500</td><td>300</td><td>500</td><td>5</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;"> SEPARCHROM PC04-300/900</td><td>300</td><td>900</td><td>5</td>
        <td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
      </tbody>
    </table>
  </div>
</div>`
  },

  "separchrom-pc06": {
    id: "separchrom-pc06",
    name: "Separchrom PC06 Columns For Preparative Chromatography",
    image: ImgSeparchromPC06,
    logo: ECom,
    bannerImg: Banner3,
    altText: "Ecom",
    videoId: "",
    meta: {
      title: "Separchrom PC06 Columns For Preparative Chromatography (DAC Columns, 50mm-1000mm ID Columns) Distributor & Service Provider In India - Ecom - Inkarp Instruments Pvt Ltd",
      description:
        "Explore the SEPARCHROM PC06 Industrial Chromatography Columns from Ecom, designed for precision, scalability, and industrial-scale purification. Distributed and supported by Inkarp Instruments across India.",
      keywords: [
        "SEPARCHROM PC06 Columns",
        "Industrial Chromatography Columns",
        "Ecom Column Systems",
        "HPLC Industrial Columns",
        "Preparative Chromatography India",
        "Inkarp Ecom Instruments",
        "Large ID Chromatography Columns",
        "Inkarp Chromatography Solutions",
        "Industrial Process Columns"
      ],
      altText: "SEPARCHROM PC06 Industrial Column",
      internalLinks: ["analytical-and-chromatography-solutions"],
      externalLinks: ["https://www.waters.com/nextgen/us/en.html"]
    },
    description: `
<div class="text-[18px] ">
  <h2 style="font-size: 24px; font-weight: bold;  margin-bottom: 1rem;"
    class="font-[MaxOT]">
    SEPARCHROM PC06 Columns for Preparative Chromatography<br> 
  </h2>
  <p><strong>UHMWPE COLUMNS FOR PREP CHROMATOGRAPHY</strong><br>
  <p style="font-size: 18px; line-height: 1.6; margin-bottom: 1rem;">
   Inkarp Instruments, in partnership with Ecom, offers Separchrom PC04 Columns, a premium solution for preparative chromatography in India. These DAC (Dynamic Axial Compression) columns, available in 50mm-1000mm ID, ensure high-efficiency separations, scalability, and reproducibility. With Inkarp Instruments' expertise and Ecom's innovative technology, we deliver comprehensive support, including installation, training, and after-sales service, to meet your laboratory needs and enhance your chromatography workflow.
  </p>
  <p style="font-size: 18px; line-height: 1.6; margin-bottom: 1rem;">
    <strong>Columns for Medium Pressure without bed compression</strong><br>
  For flash chromatography are usually intended polyethylene cartridge columns. Metal free columns are requested in some special applications too. Separlab offers Separchrom PC04 columns for both these purposes. Columns are made of high quality ultra high molecular weight polyethylene, have similar design like stainless steel columns PC01 or PC02 and are equipped with polypropylene fabrics (non woven polypropylene 10 µm pores) made frits. Piston on the input moved by a robust central screw increases the efficiency due an elimination of free space between upper sorbent layer and frit with low pressure flow distributor. Output frit with flow distributor is incorporated in output flange. Columns are compatible with nearly all organic solvents and with all water solutions. Columns are designated for low pressure and medium pressure liquid chromatography.
  </p>

  <!-- Table 1: Laboratory Applications -->
  <h2 class="text-xl text-[#E63946] font-[MaxOT] py-3" >Laboratory Columns</h2>
  <div style="overflow-x: auto;">
    <table style="width: 100%; border-collapse: collapse; font-size: 15px; border: 1px solid #ccc;">
      <thead>
        <tr style="background-color: #f5f5f5; text-align: left;">
          <th style="padding: 10px; border: 1px solid #ccc;">Type of Column</th>
          <th style="padding: 10px; border: 1px solid #ccc;">I.D. (mm)</th>
          <th style="padding: 10px; border: 1px solid #ccc;">Length (mm)</th>
          <th style="padding: 10px; border: 1px solid #ccc;">Pressure (bar)</th>
          <th style="padding: 10px; border: 1px solid #ccc;">Note</th>
        </tr>
      </thead>
      <tbody>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC06-25/50</td><td>25</td><td>50</td><td>100</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC06-25/250</td><td>25</td><td>250</td><td>100</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC06-50/250</td><td>50</td><td>250</td><td>50</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC06-50/500</td><td>50</td><td>500</td><td>50</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC06-100/250</td><td>100</td><td>250</td><td>40</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC06-100/500</td><td>100</td><td>500</td><td>40</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
      </tbody>
    </table>
  </div>

  <!-- Table 2: Industrial Applications -->
  <h2 class="text-xl text-[#E63946] font-[MaxOT] py-3">Industrial Columns</h2>
  <div style="overflow-x: auto;">
    <table style="width: 100%; border-collapse: collapse; font-size: 15px; border: 1px solid #ccc;">
      <thead>
        <tr style="background-color: #f5f5f5; text-align: left;">
          <th style="padding: 10px; border: 1px solid #ccc;">Type of Column</th>
          <th style="padding: 10px; border: 1px solid #ccc;">I.D. (mm)</th>
          <th style="padding: 10px; border: 1px solid #ccc;">Length (mm)</th>
          <th style="padding: 10px; border: 1px solid #ccc;">Pressure (bar)</th>
          <th style="padding: 10px; border: 1px solid #ccc;">Note</th>
        </tr>
      </thead>
      <tbody>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC06-100/250</td><td style="padding: 10px; border: 1px solid #ccc;">100</td><td style="padding: 10px; border: 1px solid #ccc;">250</td><td>40</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC06-100/500</td><td>100</td><td>500</td><td>40</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC06-150/300</td><td>150</td><td>300</td><td>40</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC06-150/600</td><td>150</td><td>600</td><td>40</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC06-200/400</td><td>200</td><td>400</td><td>35</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC06-200/800</td><td>200</td><td>800</td><td>35</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC06-300/300</td><td>300</td><td>300</td><td>30</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC06-300/600</td><td>300</td><td>600</td><td>30</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC06-400/200</td><td>400</td><td>200</td><td>20</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC06-400/400</td><td>400</td><td>400</td><td>20</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC06-400/800</td><td>400</td><td>800</td><td>20</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC06-500/500</td><td>500</td><td>500</td><td>10</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC06-500/1000</td><td>500</td><td>1000</td><td>10</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC06-600/600</td><td>600</td><td>600</td><td>5</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
        <tr><td style="padding: 10px; border: 1px solid #ccc;">SEPARCHROM PC06-600/1200</td><td>600</td><td>1200</td><td>5</td><td style="padding: 10px; border: 1px solid #ccc;">—</td></tr>
      </tbody>
    </table>
  </div>
</div>
`

  },

  "separchrom-pc08": {
    id: "separchrom-pc08",
    name: "Separchrom PC08 Columns For Preparative Chromatography",
    image: ImgSeparchromPC08,
    logo: ECom,
    bannerImg: Banner3,
    altText: "Ecom",
    videoId: "",
    meta: {
      title: "SEPARCHROM PC08 Columns | Industrial Chromatography Columns | Inkarp India",
      description:
        "Explore the SEPARCHROM PC08 Industrial Chromatography Columns from Ecom, designed for precision, scalability, and industrial-scale purification. Distributed and supported by Inkarp Instruments across India.",
      keywords: [
        "SEPARCHROM PC08 Columns",
        "Industrial Chromatography Columns",
        "Ecom Column Systems",
        "HPLC Industrial Columns",
        "Preparative Chromatography India",
        "Inkarp Ecom Instruments",
        "Large ID Chromatography Columns",
        "Inkarp Chromatography Solutions",
        "Industrial Process Columns"
      ],
      altText: "SEPARCHROM PC06 Industrial Column",
      internalLinks: ["analytical-and-chromatography-solutions"],
      externalLinks: ["https://www.waters.com/nextgen/us/en.html"]
    },
    description: `
<div class="text-[18px]">
  <h2 style="font-size: 24px; font-weight: bold; color: #e63946; margin-bottom: 1rem;">
    SEPARCHROM PC08 Columns for Preparative Chromatography
  </h2>
  <p style="font-size: 16px; margin-bottom: 1rem;">
    <strong>HPLC Columns for Prep Chromatography</strong>
  </p>
  <p style="font-size: 18px; line-height: 1.6; margin-bottom: 1rem;">
   Inkarp in partnership with Ecom, offers Separchrom PC08 Columns, a premium solution for preparative chromatography in India. These advanced DAC (Dynamic Axial Compression) columns, available in 50mm-1000mm ID, deliver exceptional separation efficiency, scalability, and reproducibility. We provide comprehensive support, including installation, training, and after-sales service, to optimize your chromatography workflow and meet your laboratory needs in India, ensuring maximum performance and efficiency.
  </p>
  <p style="font-size: 18px; line-height: 1.6; margin-bottom: 1rem;">

    SEPARCHROM PC08 columns are designed for high pressure, high performance preparative liquid chromatography. They are equipped by pistons on both ends. All metal parts in connection with mobile phase are made of AISI 316L stainless steel. Upper piston movement is secured by hydraulics, but in comparison with standard models, PC08 hydraulics is in incorporated into bottom column stand, own column is fixed in a robust frame and hydraulic piston press the whole column unit against a special flange in most upper part of the system.
  </p>
  <p style="font-size: 18px; line-height: 1.6; margin-bottom: 1rem;">
    PC08 columns are used for high performance separations in instances where small rigid particles are used as column filling. Only stainless steel and UHMWPE (ultra high molecular weight polyethylene) are in contact with mobile phase. Columns are resisting to all common solvents. PC08 columns with are designed for industrial separations and typically are working with flow rate 400 ml/min. – 1400 ml/min. depending on sorbent type and separation mode. Maximal column pressure is 120 bar.
  </p>
  <p style="font-size: 18px; line-height: 1.6; margin-bottom: 1rem;">
   PC08 columns are designed either for sedimentation packing with following axial compression of sorbent bed or for dynamic axial compression packing. Columns with I.D. 150 mm or 200 mm have a special stand with motor driven high pressure hydraulic aggregate and hydraulic cylinder (40 tons, 200 - 600 mm stroke, double action) which serves for sorbent pressing during the use to compensate bed volume changes as well.
  </p>
  <p style="font-size: 18px; line-height: 1.6; margin-bottom: 1rem;">
   PC08 column stand has hydraulic system in bottom part and column is fixed between hydraulic cylinder piston and upper stand flange which is connected to the stand box by five rods. Column itself can be removed from the frame without deassembling of the frame
  </p>

   <p style="font-size: 18px; line-height: 1.6; margin-bottom: 1rem;">
  Typically the PC08 column has the same design as PC 01 columns - consists of tube, I.D. 150 mm or 200 mm with the length 400 - 700 mm. The internal surface of the column is mechanically polished to attain high smoothness. The tube is provided with two screwed stainless steel flanges (tube flanges). Column pistons are equipped with Poremet® 2 frits (3 um porosity) and flow distributors.
  </p>

  <!-- Table: PC08 Column Specifications -->
  <h2 class="font-[MaxOT] text-xl text-[#E63946] py-3">PC08 Column Specifications</h2>
  <div style="overflow-x: auto;">
    <table style="width: 100%; border-collapse: separate; border-spacing: 0; font-size: 15px; border: 1px solid #ccc; box-shadow: 0 2px 8px rgba(0,0,0,0.05); border-radius: 8px; overflow: hidden;">
      <thead>
        <tr style="background-color: #f1f5f9; text-align: left; color: #1d3557;">
          <th style="padding: 12px; border-bottom: 2px solid #ccc;">Type of Column</th>
          <th style="padding: 12px; border-bottom: 2px solid #ccc;">I.D. (mm)</th>
          <th style="padding: 12px; border-bottom: 2px solid #ccc;">Length (mm)</th>
          <th style="padding: 12px; border-bottom: 2px solid #ccc;">Pressure (bar)</th>
          <th style="padding: 12px; border-bottom: 2px solid #ccc;">Note</th>
        </tr>
      </thead>
      <tbody>
        <tr style="background-color: #ffffff;">
          <td style="padding: 10px; border-bottom: 1px solid #eee;">SEPARCHROM PC08-150/500</td>
          <td style="padding: 10px; border-bottom: 1px solid #eee;">150</td>
          <td style="padding: 10px; border-bottom: 1px solid #eee;">500</td>
          <td style="padding: 10px; border-bottom: 1px solid #eee;">150</td>
          <td style="padding: 10px; border-bottom: 1px solid #eee;">—</td>
        </tr>
        <tr style="background-color: #f9fafb;">
          <td style="padding: 10px; border-bottom: 1px solid #eee;">SEPARCHROM PC08-150/700</td>
          <td style="padding: 10px; border-bottom: 1px solid #eee;">150</td>
          <td style="padding: 10px; border-bottom: 1px solid #eee;">700</td>
          <td style="padding: 10px; border-bottom: 1px solid #eee;">150</td>
          <td style="padding: 10px; border-bottom: 1px solid #eee;">—</td>
        </tr>
        <tr style="background-color: #ffffff;">
          <td style="padding: 10px; border-bottom: 1px solid #eee;">SEPARCHROM PC08-200/500</td>
          <td style="padding: 10px; border-bottom: 1px solid #eee;">200</td>
          <td style="padding: 10px; border-bottom: 1px solid #eee;">500</td>
          <td style="padding: 10px; border-bottom: 1px solid #eee;">120</td>
          <td style="padding: 10px; border-bottom: 1px solid #eee;">—</td>
        </tr>
        <tr style="background-color: #f9fafb;">
          <td style="padding: 10px;">SEPARCHROM PC08-200/700</td>
          <td style="padding: 10px;">200</td>
          <td style="padding: 10px;">700</td>
          <td style="padding: 10px;">120</td>
          <td style="padding: 10px;">—</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
`
  },

  "separpress": {
    id: "separpress",
    name: "Separpress Columns For Preparative Chromatography",
    image: ImgSeparpress,
    logo: ECom,
    bannerImg: Banner3,
    altText: "Ecom",
    videoId: "",
    meta: {
      title: "Separpress Columns For Preparative Chromatography | Industrial Chromatography Columns | Inkarp India",
      description:
        "Explore the Separpress Columns For Preparative Chromatography Columns from Ecom, designed for precision, scalability, and industrial-scale purification. Distributed and supported by Inkarp Instruments across India.",
      keywords: [
        "Separpress Columns For Preparative Chromatography",
        "Industrial Chromatography Columns",
        "Ecom Column Systems",
        "HPLC Industrial Columns",
        "Preparative Chromatography India",
        "Inkarp Ecom Instruments",
        "Large ID Chromatography Columns",
        "Inkarp Chromatography Solutions",
        "Industrial Process Columns"
      ],
      altText: "SEPARCHROM PC06 Industrial Column",
      internalLinks: ["analytical-and-chromatography-solutions"],
      externalLinks: ["https://www.waters.com/nextgen/us/en.html"]
    },
    description: `
<div class="text-[18px]">
  <h2 style="font-size: 24px; font-weight: bold; margin-bottom: 1rem;">
    SEPARPRESS Columns for Preparative Chromatography
  </h2>
  <p style="font-size: 16px; margin-bottom: 1rem;">
    <strong>Hydraulic Systems for Prep Chromatography Columns</strong>
  </p>

  <p style="font-size: 18px; line-height: 1.6; margin-bottom: 1rem;">
  Hydraulic system SEPARPRESS for prep chromatographic columns. Used to compress the piston inside the column and to compact the sorbent. Supplied as a kit that includes a hydraulic cylinder - double action (D) or with spring (S) with connecting hoses, oil pump - manual (M) or driven by motor (E) with control device - mechanical manometer (M) or electronic system with pressure gauge (E).
  </p>
 

  <!-- Table: SEPARPRESS Hydraulic Systems -->
  <h2 class="text-xl py-3 text-[#e63946] font-[MaxOT]">SEPARPRESS Hydraulic System Specifications</h2>
  <div style="overflow-x: auto;">
    <table style="width: 100%; border-collapse: separate; border-spacing: 0; font-size: 15px; border: 1px solid #ccc; box-shadow: 0 2px 8px rgba(0,0,0,0.05); border-radius: 8px; overflow: hidden;">
      <thead>
        <tr style="background-color: #f1f5f9; text-align: left; color: #1d3557;">
          <th style="padding: 12px; border-bottom: 2px solid #ccc;">Type & Specification</th>
          <th style="padding: 12px; border-bottom: 2px solid #ccc;">Power (t)</th>
          <th style="padding: 12px; border-bottom: 2px solid #ccc;">Stroke (mm)</th>
          <th style="padding: 12px; border-bottom: 2px solid #ccc;">Note</th>
        </tr>
      </thead>
      <tbody>
        ${[
        ["SEPARPRESS S005 MM 080", "5", "80"],
        ["SEPARPRESS S005 MM 180", "5", "180"],
        ["SEPARPRESS S005 MM 240", "5", "240"],
        ["SEPARPRESS D005 MM 150", "5", "150"],
        ["SEPARPRESS D010 MM 150", "10", "150"],
        ["SEPARPRESS D010 MM 250", "10", "250"],
        ["SEPARPRESS D020 MM 150", "20", "150"],
        ["SEPARPRESS D020 MM 250", "20", "250"],
        ["SEPARPRESS D030 MM 150", "30", "150"],
        ["SEPARPRESS D030 MM 250", "30", "250"],
        ["SEPARPRESS D050 MM 150", "50", "150"],
        ["SEPARPRESS D050 MM 250", "50", "250"],
        ["SEPARPRESS D100 MM 150", "100", "150"],
        ["SEPARPRESS D100 MM 350", "100", "350"],
        ["SEPARPRESS D150 MM 330", "150", "330"],
        ["SEPARPRESS D010 EE 250", "10", "250"],
        ["SEPARPRESS D020 EE 250", "20", "250"],
        ["SEPARPRESS D030 EE 250", "30", "250"],
        ["SEPARPRESS D050 EE 250", "50", "250"],
        ["SEPARPRESS D100 EE 350", "100", "350"],
        ["SEPARPRESS D150 EE 330", "150", "330"],
        ["SEPARPRESS D030 EEB 250", "30", "250"],
        ["SEPARPRESS D050 EEB 250", "50", "250"],
        ["SEPARPRESS D010 AM 250", "10", "250"],
        ["SEPARPRESS D020 AM 250", "20", "250"],
        ["SEPARPRESS D030 AM 250", "30", "250"]
      ].map(([type, power, stroke], index) => `
        <tr style="background-color: ${index % 2 === 0 ? '#ffffff' : '#f9fafb'};">
          <td style="padding: 10px; border-bottom: 1px solid #eee;">${type}</td>
          <td style="padding: 10px; border-bottom: 1px solid #eee;">${power}</td>
          <td style="padding: 10px; border-bottom: 1px solid #eee;">${stroke}</td>
          <td style="padding: 10px; border-bottom: 1px solid #eee;">—</td>
        </tr>`).join("")}
      </tbody>
    </table>
  </div>
</div>
`



  },

  "separsys-hp-400-800-fp-300-ds": {
    id: "separsys-hp-400-800-fp-300-ds",
    name: "Separsys HP 400, 800 FP, 300 DS PLC Industrial Systems",
    image: ImgSeparsys400,
    logo: ECom,
    bannerImg: Banner3,
    altText: "Ecom",
    videoId: "",
    meta: {
      title: "Separsys HP 400, 800 FP, 300 DS | Industrial Chromatography Columns | Inkarp India",
      description:
        "Explore the Separsys HP 400, 800 FP, 300 DS Columns from Ecom, designed for precision, scalability, and industrial-scale purification. Distributed and supported by Inkarp Instruments across India.",
      keywords: [
        "Separsys HP 400, 800 FP, 300 DS",
        "Industrial Chromatography Columns",
        "Ecom Column Systems",
        "HPLC Industrial Columns",
        "Preparative Chromatography India",
        "Inkarp Ecom Instruments",
        "Large ID Chromatography Columns",
        "Inkarp Chromatography Solutions",
        "Industrial Process Columns"
      ],
      altText: "Separsys HP 400, 800 FP, 300 DS",
      internalLinks: ["analytical-and-chromatography-solutions"],
      externalLinks: ["https://www.waters.com/nextgen/us/en.html"]
    },
    description: `
<div class="text-[18px]">
  <h2 style="font-size: 24px; font-weight: bold;  margin-bottom: 1rem;">
    Separsys HP 400, 800 FP, 300 DS PLC Industrial Systems
  </h2>

  <p style="font-size: 16px; margin-bottom: 1rem;">
    <strong>High-Pressure Preparative Chromatography Systems</strong>
  </p>

  <ul style="font-size: 18px; line-height: 1.6; padding-left: 1rem;" class="list-disc">
   <li>high-pressure column separchrom PC01 400 with an inside diameter 399 mm and length 1000 mm, column is packed with 15 µ spherical silica (sedimentation procedure of packing), maximum pressure 80 bar</li>
   <li>block of mobile phase delivery control (including bypass and flow reversing) provided with manual high-pressure ball valves and electronic pressure sensors to the output column fixed detector cell PLCC 15 Ex and a detector FLASH 06S DAD 600 EX</li>
   <li>three membrane pumps hydracell  P3 (up to 8 l/min. and 70 bar each, oil level control) - two are in parallel and supply the mobile phase, the third delivers the mixture to be separated</li>
   <li>remote switchboard with three units of frequency converters ABB which supply power to pump motors and allow flow changes and electronic control unit separel 01</li>
   <li>PC computer using a modified software ECOMAC to set parameters of the separation process and to monitor both detector signal and column pressure</li>
  </ul>

  <!-- Image: Middle -->
  <div style={{ textAlign: 'center', margin: '2rem 0' }}>
  <img
    src="/images/products/Ecom/Image1.png"
    alt="SEPARCHROM PC01 400 System"
    style={{
      maxWidth: '100%',
      borderRadius: '8px',
      border: '2px solid #ddd',
    }}
  />
</div>


  <!-- Section: FP 800 System -->

  <ul style="font-size: 18px; line-height: 1.6; padding-left: 1rem;" class="list-disc">
   <li>new high-pressure column separchrom PC05 800 with an inside diameter 799 mm and length 1000 mm, column is packed with 15 µ spherical silica (sedimentation procedure of packing) and equipped with a special floating piston, maximum pressure 50 bar.</li>
   <li>block of mobile phase delivery control (including bypass)  provided with air controlled high-pressure ball valves and electronic pressure sensors.</li>
   <li>to the output column is connected detector cell PLCC 15 Ex through an automatic bypass system separpass 03 (cell is in 10 m distance from the column) and a detector FLASH 06S DAD 600 EX.</li>
   <li>three membrane pumps hydracell G3 and G10 (up to 8 l/min. and 70 bar each, oil level control, 27 l/min, 70 bar for G10) – G10 supplies the mobile phase, one G3 is injecting the sample and the second moves the column piston the third delivers the mixture to be separated.</li>
   <li>remote switchboard with three units of frequency converters ABB ACS 550-01-06A9-4, which supply power to pump motors and allow flow changes and electronic control unit separel 01.</li>
   <li>PC computer using a modified software ECOMAC to set parameters of the separation process and to monitor both detector signal and column pressure.</li>
  </ul>
  <!-- Image: End -->
 <div style={{ textAlign: 'center', margin: '2rem 0' }}>
  <img
    src="/images/products/Ecom/Image2.png"
    alt="SEPARCHROM PC01 400 System"
    style={{
      maxWidth: '100%',
      borderRadius: '8px',
      border: '2px solid #ddd',
    }}
  />
</div>
 
  <ul style="font-size: 18px; line-height: 1.6; padding-left: 1rem;" class="list-disc">
    <li>hydraulic system separpress D100 EE 1300 having a power 100 tons and stroke 1300 mm, fed by an electric motor driven oil pump with pressure control, maxim oil pressure 200 bar.</li>
    <li>block of mobile phase delivery control (including bypass)  provided with manual controlled high-pressure ball valves and electronic pressure sensors.</li>
    <li>block of flow reversion which allow to change flow direction in the column.</li>  
    <li>to the output column is connected detector cell PLCC 15 Ex through an automatic bypass system separpass 03 (cell is in 10 m distance from the column) and a detector FLASH 06S DAD 600 EX.</li>
    <li>two membrane pumps hydracell G04 (up to 8 l/min. and 120 bar each, oil level control) supply the mobile phase and the sample.</li>
    <li>remote switchboard with three units of frequency converters ABB, which supply power to pump motors and allow flow changes of mobile phase, sample and oil and electronic control unit separel  04.</li>
    <li>PC computer using a modified software ECOMAC to set parameters of the separation process and to monitor both detector signal and column pressure.</li>
  </ul>
</div>
`
  },
  
}