import ThalesNano from '/src/assets/PrincipalLogos/RowOne/ThalesNano.jpg';

import ImgHcubeMiniPlus from "/images/products/ThalesNano/HcubeMiniPlus.jpg";
import ImgHcubePro from "/images/products/ThalesNano/HcubePro.jpg";
import ImgHGenieLite from "/images/products/ThalesNano/HGeneLite.jpg";
import ImgHGenie2 from "/images/products/ThalesNano/HGene2.jpg";
import ImgPhoenixII from "/images/products/ThalesNano/PhoenixFlowMeter.jpg";   // Phoenix™ II Flow Reactor
import ImgPhoenixPlatform from "/images/products/ThalesNano/PhoenixPlatform.jpg";
// NOTE: filename in your folder is 'PhotCube.jpg' (missing 'o'). Keep as-is or rename to 'PhotoCube.jpg'.
import ImgPhotoCube from "/images/products/ThalesNano/PhotCube.jpg";


import Banner1 from "/images/products/Banner/Banner1.jpg";
import Banner2 from "/images/products/Banner/Banner2.jpg";
import Banner3 from "/images/products/Banner/Banner3.jpg";



export const ThalesNanoProducts = {
  "h-cube-mini-plus": {
    id: "h-cube-mini-plus",
    name: "H-Cube® Mini Plus",
    image: ImgHcubeMiniPlus,
    bannerImg: Banner3,
    logo: ThalesNano,
    altText: "ThalesNano",
    videoId: "TYcbNOXMQWw",
    meta: {
      title: "H-Cube® Mini Plus H-Cube® Systems Distributor & Service Provider In India - Thalesnano - Inkarp Instruments Pvt Ltd",
      description:
        "Safe, powerful, and affordable flow hydrogenation reactor with in-situ H2 generation (no cylinders), up to 100 bar & 100 °C, and CatCart® packed-bed catalysts.",
      keywords: [
        "ThalesNano",
        "H-Cube",
        "H-Cube Mini Plus",
        "flow hydrogenation",
        "CatCart",
        "flow chemistry",
        "Inkarp India"
      ],
      altText: "H-Cube Mini Plus flow reactor"
    },
    description: `
<div class="ink-compact" style="font-family:Roboto;color:#333;line-height:1.7;font-size:18px;">
  <div class="gap-8 items-start">
    
    <!-- Left Column -->
    <div class="left-column space-y-2">
      <p>
       Unlock the potential of flow chemistry with ThalesNano's H-Cube Mini Plus, distributed and serviced by Inkarp Instruments. The H-Cube Mini Plus is ideal for research and development, offering precise control, reproducibility, and enhanced safety. With ThalesNano's innovative H-Cube Mini Plus and Inkarp's dedicated support.
      </p>
      <p>
       The H-Cube® Mini Plus is a safe, powerful and affordable flow reactor which generates high-pressure hydrogen with the electrolysis of water, allowing chemists to perform catalytic hydrogenations from atmospheric pressure and room temperature to 100 bar and 100 °C in minutes.
      </p>
      <p>
        Hydrogenation is one of the most important reactions in chemical synthesis, but the hazardous nature of hydrogen limits its use. The H-Cube® series have already eliminated the dangers associated with hydrogenation through the use of in situ hydrogen generation and the handling of pyrophoric catalysts by filling them in sealed catalyst cartridges (CatCarts®). This technology has been adopted by the leaders in the pharmaceutical, flavor and fragrance, fine chemical, agrochemical industries and in academia.
      </p>
      <p>The hydrogen generation system of the H-Cube® Mini Plus can be easily turned off to allow non-hydrogenation reactions to be performed as well, such as C-C coupling reactions.</p>
    </div>

    <!-- Right Column -->
    <div class="right-column">
    <div class="flex justify-center items-center">
       <h2 class="inline-block bg-[#fff4f4] font-[MaxOT] text-[#E63946] text-xl font-bold px-2 py-1 rounded-md mb-2">
        How does it work?
      </h2>
      </div>
      <ul class="prod-det list-disc pl-5 space-y-2">
       <li>The hydrogen is generated by the electrolysis of water inside the system.</li>
        <li>The HPLC pump introduces the pure solvent into the system, where it is mixed using a mixing valve with the hydrogen.</li>
        <li>The gas-liquid mixture passes through the reaction zone while the system prepares to work at the selected parameters (pressure, temperature and flow rate).</li>
        <li>When the desired parameters are achieved, the user can change the input from the solvent to the solution of the reactants.</li>
        <li>The reaction mixture passes through a packed column containing the solid catalyst (CatCart®), where the reaction takes place. The product leaves the column, but the catalyst stays behind.</li>
        <li>The product is collected in the collection vial.</li>
        <li>The reaction scale can be varied from milligrams to grams.</li>
      </ul>
    </div>
  </div>
</div>
`,
    features: [
      {
        name: "Hydrogenation without cylinders",
      },
      {
        name: "No catalyst filtration",
      },
      {
        name: "Fast reactions",
      },
      {
        name: "Easy-to-use",
      },
      {
        name: "Affordable",
      },
      { name: "Built-in video tutorial", },
      { name: "Automated hydrogen drying system", }
    ],

    advantages: [],
    highlights: [],
    faqs: [],
    techSpecs: {
      specs: {
        "Temperature Range": "Room temperature to 100 °C",
        "Pressure Range": "Atmospheric to 100 bar",
        "Flow Rate": "0.3 – 3 mL/min",
        "Maximum H₂ Production": "25–30 NmL/min",
        "Water specifications": "Deionized water with maximum conductivity of 71 nS/cm (min. resistance 14 MΩcm)",
        "Water Reservoir": "100 mL (DI, ≤ 71 nS/cm; ≥ 14 MΩ·cm)",
        "Dimensions (W×H×D)": "• Width: 217 mm (8.54″),Height: 200 mm (7.87″) with closed display, 315 mm (12.4″) with opened,Depth: 290 mm (11.42″)",
        "Weight": "7.3 kg",
        "Voltage": "100–240 V AC",
        "Typical Catalyst": "0.1–0.3 g",
        "Recommended Concentration": "0.01–1 M"
      }
    }

  },

  "h-cube-pro": {
    id: "h-cube-pro",
    name: "H-Cube® Pro ",
    image: ImgHcubePro,
    bannerImg: Banner3,
    logo: ThalesNano,
    altText: "ThalesNano",
    videoId: "",
    meta: {
      title: "H-Cube® Pro H-Cube® Systems Distributor & Service Provider In India - Thalesnano - Inkarp Instruments Pvt Ltd",
      description:
        "High-throughput hydrogenation flow reactor with in-situ H₂ generation (up to 60 NmL/min), 10–150 °C, 0.3–3 mL/min, and CatCart® compatibility — for advanced R&D and industrial applications.",
      keywords: [
        "ThalesNano", "H-Cube Pro", "flow hydrogenation", "CatCart",
        "flow chemistry", "Inkarp India"
      ],
      altText: "H-Cube Pro flow reactor"
    },
    description: `
<div class="font-roboto text-[#333] leading-relaxed text-[18px]">
  <!-- Two-column grid layout -->
  <div class="gap-6 mb-6"> 
    <!-- Left Column -->
    <div class="space-y-3">
      <p>Take your flow chemistry to the next level with halesNano's H-Cube Pro, distributed and serviced by Inkarp Instruments. The H-Cube Pro is designed for industrial-scale applications, providing - High-throughput processing, Precise control and reproducibility, Enhanced safety and efficiency Experience the cutting-edge technology of ThalesNano's H-Cube Pro and rely on Inkarp Instruments for comprehensive support, empowering your industrial applications.
      </p>
      <p>The H-Cube® Pro hydrogenation flow reactor offers high throughput and wide temperature capability for advanced applications.
      </p>
      <p>Hydrogenation is one of the most important reactions in chemical synthesis, but the hazardous nature of hydrogen limits its use. The H-Cube® series have already eliminated the dangers associated with hydrogenation through the use of in situ hydrogen generation and the handling of pyrophoric catalysts by filling them in sealed catalyst cartridges (CatCarts®). This technology has been adopted by the leaders in the pharmaceutical, flavor and fragrance, fine chemical, agrochemical industries and in academia.
      </p>
    </div>

    <!-- Right Column -->
    <div>
    <div class="flex justify-center items-center">
      <h2 class="inline-block bg-[#fff4f4] font-[MaxOT]  text-[#E63946] text-xl font-bold px-2 py-1 rounded-md mb-2">
       How does it work?
      </h2>
      </div>
      <ul class="list-disc pl-6 space-y-1 mt-2">
      <li>The hydrogen is generated by the electrolysis of water inside the system.</li>
      <li>The HPLC pump introduces the pure solvent into the system, where it is mixed using a mixing valve with the hydrogen.</li>
      <li>The gas-liquid mixture passes through the reaction zone while the system prepares to work at the selected parameters (pressure, temperature and flow rate).</li>
      <li>When the desired parameters are achieved, the user can change the input from the solvent to the solution of the reactants.</li>
      <li>The reaction mixture passes through a packed column containing the solid catalyst (CatCart®), where the reaction takes place. The product leaves the column, but the catalyst stays behind.</li>
      <li>The product is collected in the collection vial.</li>
      <li>The reaction scale can be varied from milligrams to grams.</li>
      </ul>
    </div>
  </div>

  <!-- Compatible Systems -->
  <div class="mb-6  p-5">
  <div class="flex justify-center items-center">
    <h2 class="inline-block bg-[#fff4f4] font-[MaxOT]  text-[#E63946] text-xl font-bold px-2 py-1 rounded-md mb-2">
      Compatible Systems
    </h2>
    
    </div>
    <p>The H-Cube® Pro is compatible with other reactor modules to give users chemistry capabilities beyond hydrogenation:</p>
    <ul class="list-disc pl-6 space-y-2 mt-2">
      <li>
        <strong>Gas Module™</strong> When the Gas Module™ is connected to the H-Cube® Pro, it allows the introduction of other gases than hydrogen, such as carbon monoxide, oxygen or Syngas. The user can choose from 14 different gases to be applied at up to 100 bar pressure, widening the reactor’s chemistry ability significantly.
       
      </li>
      <li><strong>Recommended gas regulators:</strong>N2 regulator: Linde C200/1A-200B\n
O2 regulator: Rhöna EN OX 03-10\n
H2 regulator: Linde fdr-200-100-380-h</li>
      <li>
        <strong>Phoenix Flow Reactor™</strong> The Phoenix Flow Reactor™ is a powerful instrument which can be heat the reaction zone up to 450 °C and is compatible with multiple types and sizes of reactors (CatCarts®, MidiCarts™, coiled reactors, metal-metal sealed catalyst columns). When connected to the H-Cube® Pro, it is possible to set up a system to perform single or double-step reactions in series and to monitor and control the whole process using the interface of the H-Cube® Pro.
      </li>
      <li>
        <strong>Autosampler™</strong> Fully automated processes can be implemented when connecting the H-Cube Pro™ with the Autosampler™ system which is ideal for performing optimization studies, catalyst screening (with the CatCart® Changer), or library production.
      </li>
    </ul>
  </div>
</div>
`,

    features: [
      {
        name: "Hydrogenation without cylinders",
        description:
          "Dual electrolytic cells enable in-situ hydrogen generation up to 60 NmL/min at pressures up to 100 bar, eliminating the need for external hydrogen cylinders and improving lab safety."
      },
      {
        name: "No catalyst filtration required",
        description:
          "Supports both 30 mm and 70 mm CatCarts® for packed-bed catalysis, removing the need for manual catalyst handling and post-reaction filtration."
      },
      {
        name: "Active heating and cooling system",
        description:
          "Integrated temperature control allows active cooling down to 10 °C and heating up to 150 °C, enabling a wide range of reaction conditions with precision."
      },
      {
        name: "User-friendly software interface",
        description:
          "Intuitive control software provides live parameter display, real-time monitoring, and data recording for reproducible and well-documented experiments."
      },
      {
        name: "Automated operation with timer function",
        description:
          "Programmable timer function allows automatic reaction runs and unattended operation, enhancing workflow efficiency and safety in continuous processes."
      }
    ],

    advantages: [],
    highlights: [],
    faqs: [],
    systemSpecs: {
      specs: {
        "Dimensions": "Height: 40 cm (15.75”) including touch screen | Width: 37 cm (14.6”) | Depth: 51 cm (20.1”)",
        "Weight": "23 kg (46.3 lbs)",
        "Power Requirements": "115–230 VAC | 5A/115VAC | 2.5A/230VAC | 47–63Hz, 300W",
        "Dimensions of HPLC Pump": "Height: 127 mm (5”) | Width: 76.2 mm (3”) | Depth: 250 mm (9.84”)",
        "Weight of HPLC Pump": "2.32 kg (5.1 lbs)",
        "HPLC Pump Power Requirements": "100–240 VAC, 1.3A, 47–63Hz, 55W",
        "Water Reservoir Capacity": "300 mL"
      }
    },
    techSpecs: {
      specs: {
        "Temperature Range": "10 – 150 °C",
        "Pressure Range": "Atmospheric to 100 bar",
        "Flow Rate": "0.3 – 3 mL/min",
        "Max H₂ Production": "60 NmL/min at 100% H₂ production",
        "Water Reservoir": "300 mL",
        "Water Specification": "Deionized; ≤ 71 nS/cm (≥ 14 MΩ·cm)",
      }
    },

  },

  "h-genie-lite": {
    id: "h-genie-lite",
    name: "H-Genie® Lite",
    image: ImgHGenieLite,
    bannerImg: Banner3,                 // swap to Banner2/3 if you prefer
    logo: ThalesNano,               // reuse your ThalesNano logo import
    altText: "ThalesNano",
    videoId: "",
    meta: {
      title: "ThalesNano H-Genie® Lite Hydrogen Gas Generator | Inkarp India",
      description:
        "On-demand hydrogen from water up to 50 bar with integrated safety, simple touchscreen control, compact footprint, and budget-friendly operation.",
      keywords: [
        "ThalesNano", "H-Genie Lite", "hydrogen generator", "50 bar",
        "flow chemistry", "fuel cell testing", "Inkarp India"
      ],
      altText: "H-Genie Lite hydrogen generator"
    },

    description: `
<div class="font-[Roboto] text-lg">
    <div class="">
      <p>
      ThalesNano's H-Genie® Lite Hydrogen Gas Generators, distributed and serviced by Inkarp Instruments Pvt Ltd in India, offer on-demand hydrogen production. Ideal for research, fuel cell testing, and chemical synthesis, the H-Genie® Lite enhances efficiency and productivity while reducing costs and environmental impact. Experience the benefits of ThalesNano's H-Genie® Lite and rely on Inkarp Instruments Pvt Ltd for comprehensive support in India.
      </p>\n
      <p>Replace cylinders with an accessibly priced, high-pressure smart hydrogen generator.</p>
    </div>
</div>
`,
    features: [
      {
        name: "Safe",
        description: "Generates H₂ from water on demand up to 50 bar; includes internal H₂ leak detectors and multiple safety interlocks for maximum operational safety."
      },
      {
        name: "Safe",
        description: "The H-Genie® Lite generates hydrogen from water on demand up to 50 bar. H-Genie® Lite is equipped with internal hydrogen leak detectors and many other safety features."
      },
      {
        name: "Simple",
        description: "With its intuitive touchscreen display, you can learn to use H-Genie® Lite in one minute. Simply set the required pressure or time and press start."
      },
      {
        name: "Budget-friendly",
        description: "By focusing on the essentials, we made the H-Genie® Lite an affordable yet lab essential, market leading hydrogen generator technology."
      },
      {
        name: "Compact",
        description: "With its compact size the H-Genie® Lite can easily fit in any fume hood and can be relocated to where it is needed."
      }
    ],

    advantages: [],
    highlights: [],
    faqs: [],
    techSpecs: {
      specs: {
        "Hydrogen production rate": "1 NL/min",
        "Output pressure range": "1–50 bar",
        "Purity": "≥ 99.9% at room temperature",
        "Water requirement": "Deionized water (recommended conductivity < 1 µS/cm)",
        "Water consumption rate": "200 mL/h",
        "Water reservoir capacity": "3 L",
        "Recommended environment": "Ventilated laboratory fume hood",
        "Unit dimensions (H × W × D)": "385 × 365 × 476 mm",
        "Unit weight": "33.7 kg",
        "Outlet parameter": "Swagelok 1/8″ stainless-steel tube fitting"
      }
    }

  },
  
  "h-genie-ii": {
    id: "h-genie-ii",
    name: "H-Genie® II ",
    image: ImgHGenie2,
    bannerImg: Banner3,              // or Banner1/Banner3
    logo: ThalesNano,            // reuse your ThalesNano logo import
    altText: "ThalesNano",
    videoId: "",
    meta: {
      title: "ThalesNano H-Genie® II Hydrogen Gas Generator | Inkarp India",
      description:
        "On-demand hydrogen from deionized water up to 100 bar, ≥99.99% purity, data export, and integrated safety — ideal for industrial, fuel cells, and power applications.",
      keywords: [
        "ThalesNano", "H-Genie II", "hydrogen generator", "100 bar",
        "fuel cell", "power generation", "flow chemistry", "Inkarp India"
      ],
      altText: "H-Genie II hydrogen generator"
    },

    description: `
<div class="font-[Roboto] text-lg">
  <div class="">
    <div class="">
      <p>
       Inkarp Instruments is the authorized distributor and service provider for ThalesNano's H-Genie II Hydrogen Gas Generators in India. Ideal for industrial-scale applications, fuel cells, and power generation, the H-Genie II provides a reliable and efficient hydrogen supply. Inkarp Instruments ensures premium support, including installation, training, and after-sales service.
      </p>
      <p>Eliminating all need for hydrogen cylinders</p>
    </div>
  </div>
</div>
`,
    features: [
      {
        name: " Hydrogen generation from deionized water – no cylinders needed",

      },
      {
        name: "High pressure to expand your chemistry capabilities",

      },
      {
        name: "Compatible with any reactors and balloons",

      },
      {
        name: "Simple setup and use",

      },
      {
        name: "Compact footprint to save space",

      },
      {
        name: "Internal hydrogen detector for improved safety",

      },
      {
        name: "Variable flow rate, pressure, and volume control",
      },

      {
        name: "Monitors hydrogen consumption with data export functionality",
      },
      {
        name: "Suitable for any laboratory or fume hood",
      }
    ],

    advantages: [],
    highlights: [],
    faqs: [],
    techSpecs: {
      specs: {
        "Hydrogen production rate": "0.1–1 NL/min",
        "Output pressure range": "1–100 bar",
        "Purity": "≥ 99.99% (4.0 @ 100 bar)",
        "Water requirement": "Deionized water (recommended conductivity < 1 µS/cm)",
        "Water consumption rate": "250 mL/h",
        "Water reservoir capacity": "3 L",
        "Recommended environment": "Ventilated laboratory fume hood",
        "Unit dimensions (H × W × D)": "345 × 365 × 460 mm",
        "Unit weight": "38 kg",
        "Outlet parameter": "Swagelok O.D. 1/8″"
      }
    },

  },

  "phoenix-ii-flow-reactor": {
    id: "phoenix-ii-flow-reactor",
    name: "Phoenix™ II Flow Reactor",
    image: ImgPhoenixII,
    bannerImg: Banner3,
    logo: ThalesNano,
    altText: "ThalesNano",
    videoId: "",
    meta: {
      title: "ThalesNano Phoenix™ II Flow Reactor | Inkarp India",
      description:
        "High-temperature (up to 450 °C) and high-pressure (up to 200 bar) flow reactor with interchangeable reactors for homogeneous and heterogeneous chemistry.",
      keywords: [
        "ThalesNano", "Phoenix II", "flow reactor", "450 °C", "200 bar",
        "CatCart", "Hastelloy", "PTFE", "flow chemistry", "Inkarp India"
      ],
      altText: "Phoenix II Flow Reactor"
    },

    description: `
<div class="font-[Roboto] text-lg">
  <div class="space-y-3">
      <p>
       Experience the power of flow chemistry with ThalesNano's Phoenix™ II Flow Reactor, distributed and serviced by Inkarp Instruments. Experience the cutting-edge technology of ThalesNano's Phoenix™ II Flow Reactor and rely on Inkarp Instruments for comprehensive support, empowering your research and industrial applications.
      </p>
      <p><strong>New and improved edition.</strong> The Phoenix™ II Flow Reactor is the improved edition of the all-purpose Phoenix™ Flow Reactor, the reactor designed for high temperature and high-pressure reactions. Both instruments are enabling the synthesis of novel compounds in a parameter space not achievable with standard laboratory equipment. Building on the advantages of its previous version, the Phoenix™ II Flow Reactor offers an extended chemical parameter window (temperature up to 450°C, pressure up to 200 bar), unparalleled versatility of reactor options for both homogeneous and heterogeneous reactions and makes chemical processes significantly safer.</p>
  </div>
  <div class="py-3">
     <div class="flex justify-center items-center">
      <h2 class="inline-block bg-[#fff4f4] font-[MaxOT]  text-[#E63946] text-xl font-bold px-2 py-1 rounded-md mb-2">
        Modules for Phoenix™ II Systems
      </h2>
      </div>
    <ul class="space-y-3">
      <li class=""><span class=" font-[MaxOT] text-[#E63946] text-xl font-bold">H-Genie® II </span> -With the H-Genie® II, you can use high purity hydrogen gas for your reactions, generated on-demand from water at pressures up to 100 bar (14.5–1450 psi) and at flow rates up to 1 NL/min, making your laboratory safer by replacing your hydrogen cylinders.</li>
      <li><span class=" font-[MaxOT] text-[#E63946] text-xl font-bold">HPLC Pump</span> -HPLC pump 10 mL/min THS – 09037
HPLC pump 50 mL/min THS – 43780
The HPLC pump is a 10 mL/min or 50 mL/min capacity unit with built-in pressure sensor (inlet pressure sensor). It is recommended to have an extra HPLC pump if multiple inlets are needed for the application.</li>
      <li><span class=" font-[MaxOT] text-[#E63946] text-xl font-bold">Pressure Module™</span> — The Pressure Module™ generates the pressure in the reaction chamber. The module contains a system valve, a pressure sensor and a 3-way valve to set the outlet (to waste or to product collection). The maximum pressure is 200 bar.</li>
      <li><span class=" font-[MaxOT] text-[#E63946] text-xl font-bold">Gas Module™</span> — When the Gas Module™ is connected to the Phoenix™ II Flow Reactor, it allows the introduction of gases, such as hydrogen, carbon monoxide, oxygen, syngas, etc. 14 different gases can be used up to 100 bar pressure, or any gas which characteristics are under the safety parameters of the system, widening the reactor’s chemistry capabilities significantly. It is also possible to use more than one Gas Module™ and mixers to introduce more than one gas at the same time.
        <div style="margin-top:6px;">
          <u>Recommended gas regulators:</u><br>
          N<sub>2</sub>: Linde C200/1A-200B<br>
          O<sub>2</sub>: Rhöna EN OX 03-10<br>
          H<sub>2</sub>: Linde FDR-200-100-380-H
        </div>
      </li>
    </ul>
  </div>
</div>
`,
    features: [
      { name: "Extended chemical parameter window: temperature up to 450°C, pressure up to 200 bar" },
      { name: "Heterogeneous and homogeneous capabilities" },
      { name: "User-friendly software interface" },
      { name: "Movable GUI touch screen" },
      { name: "Modular, versatile" },
      { name: "Rapid heating" },
      { name: "Cooling for rapid cool-down at the end of the reaction" },
      { name: "Multiple temperature sensors" },
      { name: "Intuitive, easy set-up" },
      { name: "Option of PC control" },
      { name: "Multiple Gas Modules™ and pumps can be connected" },
      { name: "Automated" },
      { name: "Simple interchange of the reaction zone" },
      { name: "Reactor options: PTFE, Hastelloy and stainless-steel coiled reactors; user-fillable metal–metal sealed cartridges; prefilled CatCarts® and MidiCarts™" },
    ],

    advantages: [],
    highlights: [],
    faqs: [],
    techSpecs: null
  },

  "phoenix-h-genie-platform": {
    id: "phoenix-h-genie-platform",
    name: "Phoenix – H-Genie® Platform",
    image: ImgPhoenixPlatform,
    bannerImg: Banner3,                 // swap to Banner2/3 if you prefer
    logo: ThalesNano,               // reuse your ThalesNano logo import
    altText: "ThalesNano",
    videoId: "",
    meta: {
      title: "ThalesNano Phoenix – H-Genie® Platform | Inkarp India",
      description:
        "Modular hydrogenation platform combining Phoenix Flow Reactor (up to 450 °C, 200 bar) with H-Genie® on-demand hydrogen (up to 100 bar, 1 NL/min) for safe, scalable flow chemistry.",
      keywords: [
        "ThalesNano", "Phoenix", "H-Genie", "hydrogenation platform",
        "flow chemistry", "450 °C", "200 bar", "CatCart", "Inkarp India"
      ],
      altText: "Phoenix – H-Genie Platform"
    },

    description: `
<div class="font-[Roboto] text-gray-800 leading-relaxed text-[18px] space-y-6">

  <div class="product-details relative block text-lg">
      <p>
       Unlock the full potential of hydrogenation reactions with ThalesNano's Phoenix - H-Genie® Platform, distributed and serviced by Inkarp Instruments. Inkarp Instruments offers premium distribution and service, ensuring expert support for your flow chemistry needs in India. With ThalesNano's cutting-edge Phoenix - H-Genie® Platform and Inkarp's dedicated support.
      </p>
      <p><strong>Hydrogenation Platform for high-demanding reactions</strong>The Phoenix™ Flow Reactor is an easy-to-use flow reactor platform designed for high temperature and high pressure reactions, enabling the synthesis of novel compounds in a parameter space not achievable with standard laboratory equipment. Its versatility allows the users to create a reaction system that suits the chemistry best.</p>
      <p>The H-Genie® is a compact hydrogen generator that utilises patented pressure cell technology to produce 4.0 purity H2 from water at pressures up to 100 bar (14.5–1450 psi) at flow rates up to 1 NL/min. The system is designed to be used in any laboratory as a safer and simpler replacement for hydrogen cylinders and to expand your chemistry capabilities.</p>
    </div>
  </div>

  <div class="block">
    <h2 class="text-lg font-semibold font-[MaxOT]  text-[#E63946] mb-2 border-l-4 border-[#BE0010] pl-3">Why This Platform</h2>
    <p>
      The combination of the H-Genie® with the Phoenix™ Flow Reactor offers unparalleled hydrogenation synthesis, scale-up, or catalyst testing capabilities.

Designed to be used safely in any discovery, development, process, petrochemical or catalyst screening lab, the hydrogenation platform combines in-situ high pressure hydrogen generation from water with high temperature reactor capability and a precise gas data monitoring system for the first time. Chemists and chemical engineers can now run hydrogen-based experiments with homogeneous or heterogeneous catalysts up to 450°C and 100 bar (200 and 300 Bar versions are available) without the need for hydrogen cylinders or hydrogen infrastructure.
    </p>
  </div>

  <div class="block">
    <h2 class="text-lg font-semibold font-[MaxOT]  text-[#E63946] mb-2 border-l-4 border-[#BE0010] pl-3">Modules</h2>
    <ul class="list-disc pl-6 space-y-2">
      <li>
        <strong>HPLC Pump</strong> — The HPLC pump is either a 10 mL/min or 50 mL/min (higher pump capacity can be provided on special request) capacity unit with built-in pressure sensor (inlet pressure sensor). It is recommended to have an extra HPLC pump if multiple inlets are needed for the application.
      </li>
      <li>
        <strong>Pressure Module™</strong> — The Pressure Module™ generates the pressure in the reaction chamber. The module contains a system valve, a pressure sensor and a 3-way valve to set the outlet (to waste or to product collection). The maximum pressure is 200 bar.
      </li>
      <li>
        <strong>Gas Module™</strong> — When the Gas Module™ is connected to the Phoenix – H-Genie® Platform, it allows, along hydrogen, the introduction of another gas, such as carbon monoxide, oxygen, syngas, etc. 14 different gases can be used up to 100 bar pressure, or any gas which characteristics are under the safety parameters of the system, widening the reactor’s chemistry capabilities significantly. It is also possible to use more than one Gas Module™ and mixers to introduce more than one gas at the same time.
        <div class="mt-2 text-sm text-gray-700">
          <u>Recommended gas regulators:</u><br>
          N<sub>2</sub>: Linde C200/1A-200B<br>
          O<sub>2</sub>: Rhöna EN OX 03-10<br>
          H<sub>2</sub>: Linde FDR-200-100-380-H
        </div>
      </li>
    </ul>
  </div>

  <div class="block">
    <h2 class="text-lg font-semibold font-[MaxOT]  text-[#E63946] mb-2 border-l-4 border-[#BE0010] pl-3">Available Reactors & Holders</h2>
    <p class="mb-3">
     The Phoenix™ Flow Reactor is a powerful and versatile heating unit capable of reaching temperatures up to 450 °C. A big selection of ready-made reactor setups are available for both homogeneous and heterogeneous applications.
    </p>
    <p>
    <strong>Packed bed reactors: </strong>  Prefilled CatCarts®  (30 mm, 70 mm long CatCarts®) and MidiCarts™ are available. We offer empty metal-metal sealed cartridges with fittings from 1/8” OD to 1” OD with 125 mm and 250 mm lengths for custom applications.
    </p>
    <p>
    <strong>Loops:  </strong>  4, 8, 16 or 32 mL stainless steel, PTFE or Hastelloy loops are available.
    </p>
    <p>
    <strong>Custom-made reactors are available as well. </strong>  This platform, arisen from the combination of the H-Genie® and Phoenix™ Flow Reactor, is fully customisable with the only limitation being the customer imagination. It therefore becomes easy to consider the combination of several instruments in series or parallel, along with multiple inputs and outputs and a wide range of solvents.
    </p>
  </div>

</div>
`,
    features: [
      {
        name: "User-friendly software interface"
      },
      {
        name: "Removable GUI touch screen"
      },
      {
        name: "Rapid heating"
      },
      {
        name: "Cooling for rapid cool down at end of reaction"
      },
      {
        name: "Internal and optional external temperature sensors"
      },
      {
        name: "Option for PC control"
      },
      {
        name: "Multiple Gas Modules™ and pumps can be connected"
      },
      {
        name: "Automated"
      },
      {
        name: "Monitoring of hydrogen consumption"
      },
      {
        name: "Monitoring of thermal changes"
      }
    ],

    advantages: [
      {
        name: "Safe",
        description: "Hydrogen on-demand from the electrolysis of water which is capable of generating up to 1 NL/min of hydrogen. Safe enough to use in any lab. No more cylinders."
      },
      {
        name: "Versatile",
        description: "Up to 450°C and 100 bar. Homogeneous and heterogeneous reactor sets are available."
      },
      {
        name: "Scalable",
        description: "Range of self-fillable cartridges or catcarts for catalyst optimization and synthesis from milligram to kilo scale quantities."
      },
      {
        name: "Precise",
        description: "In-built mass flow controller to monitor hydrogen pressure and flow-rate data. All data is exportable."
      },
      {
        name: "Fast",
        description: "Temperature, hydrogen pressure and flow rate can be changed quickly on the fly for rapid optimization."
      },
      {
        name: "Simple",
        description: "Easy to set up and learn how to use."
      },
      {
        name: "Modular",
        description: "System set-ups can be customized as per customers’ needs."
      }
    ],


    highlights: [],
    faqs: [],
    techSpecs: null
  },

  "photocube": {
    id: "photocube",
    name: "PhotoCube™",
    image: ImgPhotoCube,
    bannerImg: Banner3,          // optional: Banner1/Banner3
    logo: ThalesNano,        // reuse your ThalesNano logo import
    altText: "ThalesNano",
    videoId: "",
    meta: {
      title: "ThalesNano PhotoCube™ Photochemistry Reactor | Inkarp India",
      description:
        "Batch and flow photochemistry in one platform with 7+1 LEDs, interchangeable reactors/loops, and external thermoregulation.",
      keywords: [
        "ThalesNano", "PhotoCube", "photochemistry reactor",
        "batch and flow", "LED wavelengths", "Inkarp India"
      ],
      altText: "PhotoCube photochemistry reactor"
    },

    description: `
<p class="text-left text-[18px]">Batch and flow reactions with one reactor — flexible platform for method development and scale-up.</p>
`,

    features: [
      { Overview: "" },
      { name: "Batch and flow reactions in the same platform" },
      { name: "7+1 wavelengths in one instrument" }
    ],

    applications: [{ name: "Minisci reaction" }, { name: "Minisci reaction" }, { name: "Negishi coupling" }, { name: "Wohl–Ziegler bromination" }],

    highlights: [],
    faqs: [],
    techSpecs: {
      specs: {
        "Available wavelengths": "365, 395, 457, 500, 523, 595, 623&nbsp;nm and white",
        "Batch reactor volumes:": "4&nbsp;mL and 30&nbsp;mL glass vials",
        "Loop volumes:": "5–15&nbsp;mL",
        "Loop materials:": "FEP or PFA",
        "Temperature range": "20–80&nbsp;°C (with external thermoregulation)",
        "LED input power": " up to 128&nbsp;W/color"
      }
    },
  },

}